<?php
// module/Schedule/view/schedule/schedule/index.phtml:

$title = 'スコア一覧';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
    <tr>
        <th>id</th>
        <th>スコア</th>
        <th>ユーザ名</th>
        <th>プレイ時間</th>
        <th></th>
    </tr>
    <?php foreach ($score as $item) :?>
    <tr>
        <th><?php echo $item->id; ?></th>
        <th><?php echo $item->name;//['id']; ?></th>
        <th><?php echo $item->score;//['id']; ?></th>
        <th><?php echo $item->created_at;//['id']; ?></th>
        <th></th>
    </tr>
    <? endforeach;?>

</table>