<?php
namespace Score\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

use Score\Model\ScoreTable;

class ScoreController extends AbstractActionController{

    private $table;

    public function __construct(ScoreTable $table){
        $this->table = $table;
    }

    public function indexAction(){
        //return parent::indexAction(); // TODO: Change the autogenerated stub
        return new ViewModel([
            'score' => $this->table->fetchAll(),
        ]);
    }
    public function editAction(){

    }
}