version: '2'
services:
  memcached:
    image: memcached:1.4

  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql

  mysql:
    image: mysql:5.7
    env_file: ./.env
    ports:
      - "13306:3306"
    volumes_from:
      - data
    volumes:
      - ../application/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    container_name: mysql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
    links:
      - web
    container_name: nginx

  web:
    build: ./php-fpm72
    volumes:
      - ../:/var/www/html
    links:
      - mysql
    env_file: ./.env
    container_name: web

