#!/bin/csh

gcc -o ranking ranking.c
gcc -o server_highscore server_highscore.c
gcc -o server_insertranking server_insertranking.c

python3 MainServer.py >> log/MainServer.log &
python3 OwnScore.py >> log/OwnScore.log &
./ranking >> log/ranking.log &
./server_highscore >> log/server_highscore.log &
./server_insertranking >> log/server_insertranking.log &
